name: PetClinic

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build com Maven
      run: ./mvnw clean package -DskipTests

    - name: Deploy no Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: petclinic-web                # nome do seu App Service no Azure
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: target/*.jar
